### ISSUE TITLE
where is npm build?

### ISSUE THREAD

**Issue by shindesharad71** [StephenGrider/ReactStarter#15]
for building application for production, npm build not present in package.json please fix that.

**Comment by JorgeMadson** [comment]
I am to build it too, i made some cool modifications, and i want to build. But i am stuck in how i can do it.
@StephenGrider can you help us?

**Comment by yaochen1994** [comment]
I want to build it too but ,do not know how to add the build script in package.json, please help

**Comment by JorgeMadson** [comment]
@yaochen1994 
I found a solution here:
https://github.com/StephenGrider/ReduxSimpleStarter/issues/193
